version: "3.2"
services:
  # Apache PHP Server
  php:
    build: 
      context: php-config
    depends_on:
      - mysql
      - composer
    networks:
      - frontend
      - backend
    volumes:
      - ./src/:/var/www/html/
    ports: 
      - ${PHP_PORT}:80

  # MySQL Server
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=SREPS
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
  
  # PHPMyAdmin Server
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - backend
    depends_on: 
      - mysql
    environment: 
    - PMA_HOST=mysql
    - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - ${PMA_PORT}:80

  # PHP unit testing  
  phpunit:
    image: php:7.4-cli
    restart: "no"
    volumes:
      - ./src/:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: vendor/bin/phpunit
  
  # Composer image used to download dependencies
  composer:
    image: composer:latest
    command: install
    working_dir: /composer
    volumes: 
      - ./src/:/composer

networks:
  frontend:
  backend:

volumes: 
  data: