version: "3.2"
services:
  # Apache PHP Server
  php:
    build: 
      context: './php-config/'
    depends_on:
      - mysql
      - composer
    networks:
      - frontend
      - backend
    volumes:
      - ./src/:/var/www/html/
    ports: 
      - 8080:80
  
  # MySQL Server
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=SREPS
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
  
  # PHPMyAdmin Server
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - backend
    depends_on: 
      - mysql
    environment: 
    - PMA_HOST=mysql
    - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 8081:80

  # Composer image used to download dependencies
  composer:
    image: composer:latest
    command: install
    working_dir: /composer
    volumes: 
      - ./src/:/composer

networks:
  frontend:
  backend: